use anyhow::{bail, Context, Result};
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::process::Command;
use std::time::Instant;

use crate::adapters::agents::build_invocation;
use crate::core::context::model::ContextParseResult;
use crate::core::ralph::model::AgentType;
use crate::features::context::test_runner::{
    run_test_with_plan, run_test_with_plan_capture, TestRunnerPlan, ToolchainKind,
};
use crate::features::context::workflow_state::{AgentConversationRecord, GeneratedTestFile};

#[derive(Debug, Clone)]
pub(crate) struct RedTestClassification {
    pub test_id: String,
    pub category: String,
    pub reason: String,
    pub remediation_hint: String,
    pub is_behavioral: bool,
}

pub(crate) fn infer_rule_request(
    discovered_rule_files: &[PathBuf],
    parsed: &ContextParseResult,
    context_file: &Path,
    allowed: bool,
) -> Result<Option<String>> {
    if !allowed || discovered_rule_files.len() <= 1 {
        return Ok(None);
    }

    let mut hints = Vec::<String>::new();
    if let Some(language) = &parsed.language {
        hints.push(language.to_ascii_lowercase());
    }
    if let Some(runner) = &parsed.test_runner {
        hints.push(runner.to_ascii_lowercase());
    }

    let content = fs::read_to_string(context_file)
        .unwrap_or_default()
        .to_ascii_lowercase();
    for (token, hint) in [
        ("python", "python"),
        ("pytest", "python"),
        ("uv run", "python"),
        ("rust", "rust"),
        ("cargo", "rust"),
        ("typescript", "nextjs"),
        ("javascript", "nextjs"),
        ("node", "nextjs"),
        ("npm", "nextjs"),
    ] {
        if content.contains(token) {
            hints.push(hint.to_string());
        }
    }

    if hints.is_empty() {
        return Ok(None);
    }

    for hint in hints {
        let candidates: Vec<String> = discovered_rule_files
            .iter()
            .filter(|path| {
                let normalized = path.to_string_lossy().to_ascii_lowercase();
                normalized.starts_with(&format!("{}/", hint)) || normalized.contains(&hint)
            })
            .map(|path| path.to_string_lossy().to_string())
            .collect();
        if candidates.len() == 1 {
            println!("Inferred rule hint from context: {}", candidates[0]);
            return Ok(Some(candidates[0].clone()));
        }
    }

    Ok(None)
}

pub(crate) fn generate_test_scaffold(
    context_file: &Path,
    parsed: &ContextParseResult,
    toolchain: ToolchainKind,
) -> Result<Vec<GeneratedTestFile>> {
    let output_dir = derive_context_test_output_dir(context_file)?;
    fs::create_dir_all(&output_dir).with_context(|| {
        format!(
            "Failed to create test directory '{}'.",
            output_dir.display()
        )
    })?;

    let mut generated_files = Vec::<GeneratedTestFile>::new();
    for next_action in &parsed.next_actions {
        let test_id = &next_action.test_id;
        let file_base = sanitize_for_path(test_id);
        let target = match toolchain {
            ToolchainKind::Rust => output_dir.join(format!("{}.rs", file_base)),
            ToolchainKind::Python => output_dir.join(format!("test_{}.py", file_base)),
            ToolchainKind::Node => output_dir.join(format!("{}.test.js", file_base)),
            ToolchainKind::Unknown => output_dir.join(format!("{}.txt", file_base)),
        };

        if !target.exists() {
            let mut content = match toolchain {
                ToolchainKind::Rust => {
                    "#![allow(clippy::panic)]\n\n// Generated by `opennexus orchestration`.\n\n"
                        .to_string()
                }
                ToolchainKind::Python => {
                    "# Generated by `opennexus orchestration`.\n\n".to_string()
                }
                ToolchainKind::Node => "// Generated by `opennexus orchestration`.\n\n".to_string(),
                ToolchainKind::Unknown => {
                    "# Generated by `opennexus orchestration`.\n\n".to_string()
                }
            };
            match toolchain {
                ToolchainKind::Python | ToolchainKind::Unknown => {
                    content.push_str(&format!("# Intent: {}\n", next_action.description));
                }
                _ => {
                    content.push_str(&format!("// Intent: {}\n", next_action.description));
                }
            }

            match toolchain {
                ToolchainKind::Rust => {
                    content.push_str("#[test]\n");
                    content.push_str(&format!("fn test_{}() {{\n", test_id));
                    content.push_str("    panic!(\"Generated CDD scaffold test. Implement behavior to replace this placeholder.\");\n");
                    content.push_str("}\n");
                }
                ToolchainKind::Python => {
                    content.push_str(&format!("def test_{}():\n", test_id));
                    content.push_str("    raise AssertionError(\"Generated CDD scaffold test. Implement behavior to replace this placeholder.\")\n");
                }
                ToolchainKind::Node => {
                    content.push_str(&format!("test('{}', () => {{\n", test_id));
                    content.push_str("  throw new Error('Generated CDD scaffold test. Implement behavior to replace this placeholder.');\n");
                    content.push_str("});\n");
                }
                ToolchainKind::Unknown => {
                    content.push_str(&format!("- {}\n", test_id));
                }
            }

            fs::write(&target, content).with_context(|| {
                format!(
                    "Unable to write generated test scaffold '{}'.",
                    target.display()
                )
            })?;
        }

        generated_files.push(GeneratedTestFile {
            path: target,
            test_id: test_id.to_string(),
            description: next_action.description.clone(),
        });
    }

    Ok(generated_files)
}

pub(crate) fn derive_context_test_output_dir(context_file: &Path) -> Result<PathBuf> {
    let mut components = Vec::<String>::new();
    let mut found_context_root = false;

    for component in context_file.components() {
        let Component::Normal(part) = component else {
            continue;
        };
        let part = part.to_string_lossy();
        if found_context_root {
            components.push(part.to_string());
            continue;
        }
        if part == "context" {
            found_context_root = true;
        }
    }

    if components.is_empty() {
        bail!(
            "Context file '{}' is not under a 'context/' directory. Expected pattern: .../context/<project>/<feature>/<context-file>.md",
            context_file.display()
        );
    }

    let file_name = components
        .pop()
        .and_then(|name| Path::new(&name).file_stem().map(|stem| stem.to_owned()))
        .and_then(|stem| stem.to_str().map(|value| value.to_string()))
        .unwrap_or_else(|| "context".to_string());

    let mut output_dir = PathBuf::from("tests");
    for folder in components {
        output_dir.push(sanitize_for_path(&folder));
    }
    output_dir.push(sanitize_for_path(&file_name));
    Ok(output_dir)
}

pub(crate) fn sanitize_for_path(input: &str) -> String {
    let mut value = input
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
                ch
            } else {
                '_'
            }
        })
        .collect::<String>()
        .to_ascii_lowercase();
    while value.contains("__") {
        value = value.replace("__", "_");
    }
    let trimmed = value.trim_matches('_').to_string();
    if trimmed.is_empty() {
        "context".to_string()
    } else {
        trimmed
    }
}

pub(crate) fn run_agent_stage(
    stage: &str,
    prompt: &str,
    model: Option<&str>,
) -> Result<AgentConversationRecord> {
    let model_id = model.filter(|value| !value.trim().is_empty()).unwrap_or("");
    let invocation = build_invocation(
        AgentType::Opencode,
        prompt,
        model_id,
        true,
        &[],
        false,
        None,
    );
    let started = Instant::now();
    let output = Command::new(&invocation.command)
        .args(&invocation.args)
        .envs(&invocation.env)
        .output()
        .with_context(|| {
            format!(
                "Failed to execute {} agent command '{}'.",
                stage, invocation.command
            )
        })?;

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    let latency_ms = (started.elapsed().as_millis() as i64).max(1);
    let estimated_token_usage = estimate_token_usage(prompt, &stdout, &stderr);
    let terminal_status = if output.status.success() {
        "success".to_string()
    } else {
        format!("exit:{}", output.status.code().unwrap_or(-1))
    };
    if !output.status.success() {
        bail!(
            "{} agent exited with status {}. stderr: {}",
            stage,
            output.status.code().unwrap_or(-1),
            stderr.trim()
        );
    }

    Ok(AgentConversationRecord {
        stage: stage.to_string(),
        prompt: prompt.to_string(),
        stdout,
        stderr,
        success: true,
        latency_ms,
        terminal_status,
        model_id: if model_id.is_empty() {
            "opencode/default".to_string()
        } else {
            model_id.to_string()
        },
        estimated_token_usage,
    })
}

fn estimate_token_usage(prompt: &str, stdout: &str, stderr: &str) -> i64 {
    let total_chars = prompt.len() + stdout.len() + stderr.len();
    ((total_chars as i64) / 4).max(1)
}

pub(crate) fn build_red_test_author_prompt(
    context_file: &Path,
    parsed: &ContextParseResult,
    selected_rule: Option<&Path>,
    runner_plan: &TestRunnerPlan,
    generated_files: &[GeneratedTestFile],
) -> Result<String> {
    let files_block = generated_files
        .iter()
        .map(|file| {
            format!(
                "- file: {}\n  test_id: {}\n  intent: {}",
                file.path.display(),
                file.test_id,
                file.description
            )
        })
        .collect::<Vec<String>>()
        .join("\n");

    let rule_block = if let Some(rule_path) = selected_rule {
        let rule_text = fs::read_to_string(rule_path).with_context(|| {
            format!(
                "Unable to read selected rule file '{}'.",
                rule_path.display()
            )
        })?;
        format!(
            "Hard constraint: you MUST follow this rule file without exception:\nPath: {}\n\n{}",
            rule_path.display(),
            rule_text
        )
    } else {
        "No coding rule file selected; proceed with repository conventions.".to_string()
    };

    Ok(format!(
        "You are generating RED tests only for orchestration.\n\nContext file: {}\nContext id: {}\n\nGenerated scaffold files to fill (one test per file):\n{}\n\nTest command template: {}\n\nRules inspired by nexus-context-generate-red-tests:\n- Keep one test per file\n- Use test identifier exactly (already normalized)\n- Write test logic expected to fail for behavioral reasons\n- Do not produce syntax errors or collection/import failures\n- Do not implement production code\n- Do not modify files outside listed test files\n\n{}\n\nWrite concrete failing assertions in each listed file now.",
        context_file.display(),
        parsed.context_id,
        files_block,
        runner_plan.verify_command_template,
        rule_block,
    ))
}

pub(crate) fn build_coder_prompt(
    context_file: &Path,
    parsed: &ContextParseResult,
    selected_rule: Option<&Path>,
    runner_plan: &TestRunnerPlan,
    iteration: usize,
    max_iterations: usize,
) -> Result<String> {
    let tests_block = parsed.tests.join("\n- ");
    let next_actions_block = parsed
        .next_actions
        .iter()
        .map(|action| format!("- {} -> {}", action.description, action.test_id))
        .collect::<Vec<String>>()
        .join("\n");
    let rule_block = if let Some(rule_path) = selected_rule {
        let rule_text = fs::read_to_string(rule_path).with_context(|| {
            format!(
                "Unable to read selected rule file '{}'.",
                rule_path.display()
            )
        })?;
        format!(
            "Hard constraint: you MUST follow this rule file without exception:\nPath: {}\n\n{}",
            rule_path.display(),
            rule_text
        )
    } else {
        "No coding rule file selected; proceed with repository conventions.".to_string()
    };

    Ok(format!(
        "Orchestration implementation iteration {}/{}\n\nContext file: {}\nContext id: {}\n\nNext Actions:\n{}\n\nTarget tests:\n- {}\n\nVerification command template: {}\n\n{}\n\nGuardrails:\n- Do not modify generated or existing tests in tests/\n- Implement production code only\n- Keep edits minimal, deterministic, and limited to relevant files\n\nImplement code changes that satisfy all target tests.",
        iteration,
        max_iterations,
        context_file.display(),
        parsed.context_id,
        next_actions_block,
        tests_block,
        runner_plan.verify_command_template,
        rule_block,
    ))
}

pub(crate) fn classify_generated_red_tests(
    generated_files: &[GeneratedTestFile],
    plan: &TestRunnerPlan,
    syntax_failure_markers: &[String],
) -> Result<Vec<RedTestClassification>> {
    let mut classifications = Vec::<RedTestClassification>::new();
    for file in generated_files {
        let output = run_test_with_plan_capture(plan, &file.test_id).with_context(|| {
            format!(
                "Failed to execute generated red test '{}' using '{}'.",
                file.test_id, plan.verify_command_template
            )
        })?;
        if output.status.success() {
            classifications.push(RedTestClassification {
                test_id: file.test_id.clone(),
                category: "non_behavioral".to_string(),
                reason: format!(
                    "red test '{}' unexpectedly passed in red phase",
                    file.test_id
                ),
                remediation_hint:
                    "Ensure generated tests assert not-yet-implemented behavior and fail intentionally before coding."
                        .to_string(),
                is_behavioral: false,
            });
            continue;
        }
        let combined = format!(
            "{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        )
        .to_ascii_lowercase();
        if looks_like_syntax_or_collection_failure(&combined, syntax_failure_markers) {
            classifications.push(RedTestClassification {
                test_id: file.test_id.clone(),
                category: "non_behavioral".to_string(),
                reason: format!(
                    "generated red test '{}' failed due to syntax/import/collection/setup issue",
                    file.test_id
                ),
                remediation_hint:
                    "Fix syntax/import/runtime setup for this test; red gate requires behavioral assertion failures only."
                        .to_string(),
                is_behavioral: false,
            });
            continue;
        }

        classifications.push(RedTestClassification {
            test_id: file.test_id.clone(),
            category: "behavioral".to_string(),
            reason: "failed as expected during red phase".to_string(),
            remediation_hint:
                "No action required for red gate; proceed to implementation after all tests are behaviorally red."
                    .to_string(),
            is_behavioral: true,
        });
    }
    Ok(classifications)
}

pub(crate) fn validate_generated_tests(test_ids: &[String], plan: &TestRunnerPlan) -> Result<bool> {
    let mut all_passed = true;
    for test_id in test_ids {
        let passed = run_test_with_plan(plan, test_id).with_context(|| {
            format!(
                "Failed to execute resolved test command for '{}' (template='{}').",
                test_id, plan.verify_command_template
            )
        })?;
        if !passed {
            all_passed = false;
        }
    }
    Ok(all_passed)
}

fn looks_like_syntax_or_collection_failure(output: &str, markers: &[String]) -> bool {
    markers
        .iter()
        .any(|needle| !needle.trim().is_empty() && output.contains(&needle.to_ascii_lowercase()))
}

#[cfg(test)]
mod tests {
    use super::estimate_token_usage;

    #[test]
    fn token_estimate_is_non_zero_for_non_empty_payloads() {
        let estimate = estimate_token_usage("hello", "world", "");
        assert!(estimate > 0);
    }
}
